services:
  db:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres
    volumes:
      - pg:/var/lib/postgresql/data
  web:
    build:
      context: .
      target: final
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8001:8000"
    volumes:
      - .:/code

volumes:
  pg: