# Generated by Django 4.0.5 on 2022-06-19 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('required', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleLineTextColumnEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleLineTextColumn',
            fields=[
                ('column_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdefinedtables.column')),
            ],
            bases=('userdefinedtables.column',),
        ),
        migrations.CreateModel(
            name='SingleLineOfTextColumn',
            fields=[
                ('column_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userdefinedtables.column')),
                ('maximum_length', models.PositiveSmallIntegerField(default=255)),
            ],
            bases=('userdefinedtables.column',),
        ),
        migrations.AddField(
            model_name='column',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_columns', to='userdefinedtables.list'),
        ),
        migrations.CreateModel(
            name='SingleLineOfTextColumnEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='userdefinedtables.singlelineoftextcolumn')),
            ],
        ),
        migrations.AddConstraint(
            model_name='singlelineoftextcolumn',
            constraint=models.CheckConstraint(check=models.Q(('maximum_length__lte', 255)), name='maximum_length cannot exceed 255'),
        ),
        migrations.AddField(
            model_name='multiplelinetextcolumnentry',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='userdefinedtables.multiplelinetextcolumn'),
        ),
        migrations.AddConstraint(
            model_name='column',
            constraint=models.UniqueConstraint(fields=('name', 'list'), name='name cannot occur twice in list'),
        ),
    ]
